name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600

    - name: Build container image
      run: docker build -t registry.digitalocean.com/$(echo $GITHUB_REPOSITORY):$(date +'%Y-%m-%d-')$(echo $GITHUB_SHA | head -c7 ) .

    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/$(echo $GITHUB_REPOSITORY):$(date +'%Y-%m-%d-')$(echo $GITHUB_SHA | head -c7 )